
const {workouts,meals}=window.APP_DATA;
const START=new Date(2026,6,27),DAYS=56,KEY='courtneyResetPremiumV4';
let old=JSON.parse(localStorage.getItem('courtneyResetV1')||'null');
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{checks:{},sets:{},water:{},mealDone:{},mealSwaps:{},weights:{},notes:{},shopping:{},checkins:{},celebrated:{}};
function dayNum(d){return Math.floor(new Date(d.getFullYear(),d.getMonth(),d.getDate(),12).getTime()/86400000)}
function status(){let e=dayNum(new Date())-dayNum(START);if(e<0)return{stage:'countdown',left:-e,week:1,day:0,n:0};if(e>=DAYS)return{stage:'complete',week:8,day:6,n:56};return{stage:'active',week:Math.floor(e/7)+1,day:e%7,n:e+1}}
const s=status(),w=s.week,d=s.day,work=workouts[d],dk=`w${w}d${d}`;
const $=x=>document.getElementById(x);function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function phaseSets(base,i){return w>=5&&i<2?base+1:base}function pct(n,t){return t?Math.round(n/t*100):0}
function selectedMeals(){let types=['Breakfast','Lunch','Snack','Dinner'];return types.map((type,i)=>{let arr=meals.filter(m=>m.type===type),off=state.mealSwaps[`${dk}-${type}`]||0;return arr[(w+d+i+off)%arr.length]})}
function taskKeys(){let ks=[`${dk}-walk`];work.ex.forEach((e,i)=>{for(let n=1;n<=phaseSets(e.sets,i);n++)ks.push(`${dk}-ex${i}-set${n}`)});return ks}
function dailyPct(){let ks=taskKeys();return pct(ks.filter(k=>state.checks[k]).length,ks.length)}
function waterCount(){return[1,2,3,4,5].filter(i=>state.water[`${dk}-${i}`]).length}
function proteinData(){let list=selectedMeals(),done=list.filter(m=>state.mealDone[`${dk}-${m.type}`]);return{done:done.reduce((a,m)=>a+m.protein,0),total:list.reduce((a,m)=>a+m.protein,0)}}
function programProgress(){let done=0,total=0;for(let ww=1;ww<=8;ww++)for(let dd=0;dd<7;dd++){let wo=workouts[dd],k=`w${ww}d${dd}`;total++;if(state.checks[`${k}-walk`])done++;total++;if(wo.ex.every((e,i)=>Array.from({length:ww>=5&&i<2?e.sets+1:e.sets},(_,n)=>state.checks[`${k}-ex${i}-set${n+1}`]).every(Boolean)))done++}return pct(done,total)}
function setRing(el,val){el.style.background=`conic-gradient(var(--sage) ${val}%,#e2e5df ${val}%)`}
function renderHeader(){todayDate.textContent=new Intl.DateTimeFormat('en-AU',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}
function renderToday(){if(s.stage==='countdown')countdownCard.innerHTML=`<span class="eyebrow" style="color:#eef4eb">Your reset begins</span><h2>Monday 27 July</h2><div class="countdown">${s.left} ${s.left===1?'day':'days'}</div><p>Your first workout is ready: Glutes & Legs.</p>`;else if(s.stage==='complete')countdownCard.innerHTML='<h2>Eight weeks complete 🎉</h2><p>Take your final measurements and celebrate everything you achieved.</p>';else countdownCard.innerHTML=`<span class="eyebrow" style="color:#eef4eb">Day ${s.n} of 56</span><h2>Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, Courtney</h2><p>${work.icon} Week ${w} · ${work.day} · ${work.focus}</p>`;
 let dp=dailyPct(),wc=waterCount(),pd=proteinData();movePct.textContent=dp+'%';waterPct.textContent=pct(wc,4)+'%';proteinPct.textContent=pct(pd.done,pd.total)+'%';setRing(moveRing,dp);setRing(waterRing,pct(wc,4));setRing(proteinRing,pct(pd.done,pd.total));focusTitle.textContent=`${work.icon} ${work.focus}`;dayBadge.textContent=`Week ${w}`;
 todayQuick.innerHTML=[['walk',`${work.walk} min walking pad`],['water','Drink at least 2 L water'],['protein','Include protein with meals'],['stretch','Complete your stretch']].map(([x,t])=>`<label class="quick"><input type="checkbox" data-quick="${x}" ${quickDone(x)?'checked':''}><b>${t}</b></label>`).join('');
 document.querySelectorAll('[data-quick]').forEach(x=>x.onchange=()=>quickToggle(x.dataset.quick,x.checked));
 streak.textContent=calcStreak()+' days';programPct.textContent=programProgress()+'%';coachText.textContent=s.stage==='countdown'?'Set out your mat, dumbbells and booty band. You are all ready for Monday.':coachMessages[d];
 mealPreview.innerHTML=selectedMeals().map(m=>`<div class="meal-mini"><div><b>${m.type}</b><small>${m.name}</small></div><span>${m.protein}g protein</span></div>`).join('')}
const coachMessages=['Today is about glutes, not punishment. Slow reps and good form will do more than rushing.','Strong arms and a strong back make everyday life easier. Keep your ribs down during presses.','Move gently today. Pilates should feel controlled, not frantic.','Second glute day — use the chair for balance and make every rep count.','Finish the week feeling capable, not destroyed. Quality over speed.','Put on an audiobook and make the long walk enjoyable.','Recovery is part of the plan. Reset your space and be proud of the week.'];
function quickDone(x){if(x==='walk')return !!state.checks[`${dk}-walk`];if(x==='water')return waterCount()>=4;if(x==='protein')return selectedMeals().filter(m=>state.mealDone[`${dk}-${m.type}`]).length>=3;if(x==='stretch')return !!state.checks[`${dk}-stretch`]}
function quickToggle(x,v){if(x==='walk')state.checks[`${dk}-walk`]=v;if(x==='water')for(let i=1;i<=4;i++)state.water[`${dk}-${i}`]=v;if(x==='protein')selectedMeals().forEach(m=>state.mealDone[`${dk}-${m.type}`]=v);if(x==='stretch')state.checks[`${dk}-stretch`]=v;save()}
function renderWorkout(){workoutDay.textContent=`Week ${w} · ${work.day}`;workoutTitle.textContent=`${work.icon} ${work.focus}`;walkTitle.textContent=`${work.walk} minute walking-pad walk`;walkDone.checked=!!state.checks[`${dk}-walk`];walkDone.onchange=()=>{state.checks[`${dk}-walk`]=walkDone.checked;celebrate();save()};exerciseList.innerHTML=work.ex.map((e,i)=>{let sets=phaseSets(e.sets,i);return`<article class="exercise-card"><div class="exercise-head"><div><h3>${e.name}</h3><div class="exercise-meta">${sets} sets · ${e.reps} · ${e.rest?e.rest+' sec rest':'no timer'}</div></div><button class="text-btn guide-btn" data-ex="${i}">How to</button></div><div class="sets">${Array.from({length:sets},(_,n)=>`<label class="set-pill"><input class="set-check" type="checkbox" data-set="${i}-${n+1}" ${state.checks[`${dk}-ex${i}-set${n+1}`]?'checked':''}>Set ${n+1}</label>`).join('')}</div><div class="weight-row"><label>Weight used<input type="text" data-weight="${i}" value="${state.weights[`${dk}-${i}`]||''}" placeholder="e.g. 5 kg"></label><label>Reps completed<input type="text" data-reps="${i}" value="${state.weights[`${dk}-${i}-reps`]||''}" placeholder="e.g. 10, 10, 9"></label></div><div class="exercise-actions"><button class="outline timer-btn" data-seconds="${e.rest||45}">Rest timer</button><button class="outline guide-btn" data-ex="${i}">Technique</button></div></article>`}).join('');document.querySelectorAll('[data-set]').forEach(x=>x.onchange=()=>{let[a,b]=x.dataset.set.split('-');state.checks[`${dk}-ex${a}-set${b}`]=x.checked;celebrate();save()});document.querySelectorAll('[data-weight]').forEach(x=>x.oninput=()=>{state.weights[`${dk}-${x.dataset.weight}`]=x.value;persist()});document.querySelectorAll('[data-reps]').forEach(x=>x.oninput=()=>{state.weights[`${dk}-${x.dataset.reps}-reps`]=x.value;persist()});document.querySelectorAll('.guide-btn').forEach(x=>x.onclick=()=>openGuide(work.ex[x.dataset.ex]));document.querySelectorAll('.timer-btn').forEach(x=>x.onclick=()=>openTimer(+x.dataset.seconds));workoutNotes.value=state.notes[dk]||'';workoutNotes.oninput=()=>{state.notes[dk]=workoutNotes.value;persist()}}
function renderMeals(){let list=selectedMeals();calTotal.textContent=list.reduce((a,m)=>a+m.cal,0);proteinTotal.textContent=list.reduce((a,m)=>a+m.protein,0)+'g';waterTotal.textContent=(waterCount()*.5).toFixed(1)+'L';mealList.innerHTML=list.map((m,i)=>`<article class="meal-card"><div class="meal-top"><div><span class="eyebrow">${m.type}</span><h3>${m.name}</h3></div><input class="meal-check" type="checkbox" data-mealdone="${m.type}" ${state.mealDone[`${dk}-${m.type}`]?'checked':''}></div><div class="macro">${m.cal} calories · ${m.protein}g protein</div><div class="ingredients">${m.ingredients.map(x=>`<span class="chip">${x}</span>`).join('')}</div><p class="sub" style="margin-top:12px">${m.method}</p><button class="outline swap-one" data-type="${m.type}">Swap ${m.type.toLowerCase()}</button></article>`).join('');document.querySelectorAll('[data-mealdone]').forEach(x=>x.onchange=()=>{state.mealDone[`${dk}-${x.dataset.mealdone}`]=x.checked;save()});document.querySelectorAll('.swap-one').forEach(x=>x.onclick=()=>{let k=`${dk}-${x.dataset.type}`;state.mealSwaps[k]=(state.mealSwaps[k]||0)+1;save()});waterGrid.innerHTML=Array.from({length:5},(_,i)=>`<button class="water-btn ${state.water[`${dk}-${i+1}`]?'done':''}" data-water="${i+1}">${(i+1)*500}<small>mL</small></button>`).join('');document.querySelectorAll('[data-water]').forEach(x=>x.onclick=()=>{state.water[`${dk}-${x.dataset.water}`]=!state.water[`${dk}-${x.dataset.water}`];save()})}
function weeklyIngredients(){let set=new Set;for(let dd=0;dd<7;dd++){let oldd=d;let types=['Breakfast','Lunch','Snack','Dinner'];types.forEach((type,i)=>{let arr=meals.filter(m=>m.type===type),off=state.mealSwaps[`w${w}d${dd}-${type}`]||0,m=arr[(w+dd+i+off)%arr.length];m.ingredients.forEach(x=>set.add(x))})}return[...set].sort()}
function renderShop(){let groups={'Weekly groceries':weeklyIngredients(),'Equipment':['Fabric booty bands (light, medium, heavy)','Long resistance band','Core sliders (optional)','Foam roller (optional)','Ankle weights (optional)']};shoppingList.innerHTML=Object.entries(groups).map(([g,items])=>`<section class="shop-group"><h3>${g}</h3>${items.map(x=>`<label class="shop-row"><input class="shop-check" type="checkbox" data-shop="${x}" ${state.shopping[x]?'checked':''}><span>${x}</span></label>`).join('')}</section>`).join('');document.querySelectorAll('[data-shop]').forEach(x=>x.onchange=()=>{state.shopping[x.dataset.shop]=x.checked;persist()})}
function renderProgress(){progressWeek.textContent=`Week ${w}`;let checks=Object.keys(state.checks).filter(k=>state.checks[k]);workoutsDone.textContent=checks.filter(k=>k.endsWith('-walk')).length;exercisesDone.textContent=checks.filter(k=>k.includes('-ex')).length;renderChart();let ach=[['🌱','First step',checks.length>0],['🔥','3-day streak',calcStreak()>=3],['💧','Hydrated',waterCount()>=4],['🍑','Glute day',workoutsDone.textContent>=1],['⭐','Week complete',programProgress()>=12],['🏆','8 weeks',programProgress()===100]];achievements.innerHTML=ach.map(a=>`<div class="achievement ${a[2]?'unlocked':''}"><span>${a[0]}</span><b>${a[1]}</b></div>`).join('')}
function renderChart(){let pts=Object.entries(state.checkins).filter(([,x])=>x.weight).sort((a,b)=>+a[0]-+b[0]);chartEmpty.style.display=pts.length?'none':'block';weightChart.innerHTML='';if(!pts.length)return;let vals=pts.map(x=>+x[1].weight),mn=Math.min(...vals)-1,mx=Math.max(...vals)+1;let coords=pts.map(([ww,x],i)=>[40+i*(520/Math.max(1,pts.length-1)),190-(+x.weight-mn)/(mx-mn)*150]);weightChart.innerHTML=`<line x1="40" y1="190" x2="560" y2="190" stroke="#d8d3ca"/><polyline points="${coords.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#5f715a" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/>${coords.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="7" fill="#7f9079"/><text x="${p[0]}" y="${p[1]-14}" text-anchor="middle" font-size="14">${vals[i]}kg</text><text x="${p[0]}" y="212" text-anchor="middle" font-size="12">W${pts[i][0]}</text>`).join('')}`}
function calcStreak(){let n=0;for(let ww=1;ww<=w;ww++)for(let dd=0;dd<7;dd++){if(ww===w&&dd>d)break;let k=`w${ww}d${dd}`;if(state.checks[`${k}-walk`])n++;else if(!(ww===w&&dd===d))n=0}return n}
function openGuide(e){modalTitle.textContent=e.name;modalHow.textContent=e.how;modalEasy.textContent=e.easy;modalHard.textContent=e.hard;exerciseModal.showModal()}
let timer=60,timerInt=null;function openTimer(n){timer=n;timerValue.textContent=timer;timerToggle.textContent='Start';clearInterval(timerInt);timerModal.showModal()}function timerTick(){if(timer<=0){clearInterval(timerInt);timerInt=null;timerToggle.textContent='Start';navigator.vibrate?.(200);return}timer--;timerValue.textContent=timer}
function celebrate(){if(dailyPct()===100&&!state.celebrated[dk]){state.celebrated[dk]=true;for(let i=0;i<45;i++){let p=document.createElement('i');p.className='confetti-piece';p.style.left=Math.random()*100+'%';p.style.background=['#7f9079','#b89655','#b46f72','#d8c5a5'][i%4];p.style.animationDelay=Math.random()*.6+'s';confetti.appendChild(p);setTimeout(()=>p.remove(),2500)}}}
function persist(){localStorage.setItem(KEY,JSON.stringify(state))}function render(){renderHeader();renderToday();renderWorkout();renderMeals();renderShop();renderProgress();persist()}
function go(id){document.querySelectorAll('.page,.nav').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelector(`.nav[data-go="${id}"]`)?.classList.add('active');scrollTo(0,0)}
document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));document.querySelectorAll('.modal-close').forEach(x=>x.onclick=()=>x.closest('dialog').close());swapAll.onclick=()=>{['Breakfast','Lunch','Snack','Dinner'].forEach(t=>{let k=`${dk}-${t}`;state.mealSwaps[k]=(state.mealSwaps[k]||0)+1});save()};clearShop.onclick=()=>{state.shopping={};save()};saveCheckin.onclick=()=>{state.checkins[w]={weight:weight.value,waist:waist.value,hips:hips.value,energy:energy.value,win:win.value};save();alert('Week '+w+' saved')};exportBtn.onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='courtney-reset-backup.json';a.click()};importFile.onchange=async()=>{try{state=JSON.parse(await importFile.files[0].text());save()}catch{alert('That file could not be read')}};resetBtn.onclick=()=>{if(confirm('Reset all progress?')){localStorage.removeItem(KEY);location.reload()}};timerToggle.onclick=()=>{if(timerInt){clearInterval(timerInt);timerInt=null;timerToggle.textContent='Start'}else{timerInt=setInterval(timerTick,1000);timerToggle.textContent='Pause'}};timerMinus.onclick=()=>{timer=Math.max(0,timer-15);timerValue.textContent=timer};timerPlus.onclick=()=>{timer+=15;timerValue.textContent=timer};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=4').catch(()=>{}));render();
